spring.datasource.url=jdbc:postgresql://localhost/pedidos
spring.datasource.username=postgres
spring.datasource.password=ebert123
spring.datasource.driver-class-name=org.postgresql.Driver

# Dialeto PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Criar/atualizar tabelas
spring.jpa.hibernate.ddl-auto=update

# Mostrar SQL no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=30000


spring.datasource.hikari.leak-detection-threshold=300000